src/frustum.rs, src/intersect.rs, tests/point.rs
Just checked it with [clippy](https://github.com/Manishearth/rust-clippy) and fixed some warnings.
=> Clippy fixes

CONTRIBUTING.md, README.md, src/aabb.rs, src/bound.rs, src/frustum.rs, src/intersect.rs, src/line.rs, src/plane.rs, src/ray.rs, src/sphere.rs, tests/aabb.rs, tests/frustum.rs, tests/plane.rs, tests/sphere.rs
- All code was formatted with `cargo fmt`
- README was updated (not sure about this, but we definitely should state out that it's not original repo)
- Added CONTRIBUTING.md (small part, but I suppose it's enough for now)
=> Updated readme

Cargo.toml, src/aabb.rs, src/lib.rs
=> Aabb refactor

src/aabb.rs, src/bound.rs, src/frustum.rs, src/lib.rs, src/ray.rs, src/sphere.rs, tests/bound.rs, tests/frustum.rs, tests/point.rs
=> Bound trait object

src/aabb.rs, src/intersect.rs, src/ray.rs, src/sphere.rs, tests/aabb.rs, tests/plane.rs, tests/point.rs, tests/sphere.rs
It makes API more "Rusty-way" (maybe) and allows constructing APIs that generic over number of dimensions. See [this discussion in gitter](https://gitter.im/amethyst/general?at=59940f23c101bc4e3a223e83)
@kvark r?
cc @Rhuagh
=> Discrete and Continuous traits rework

src/aabb.rs, tests/aabb.rs
Also adding intersection tests for reverse order aabb vs ray/ray vs aabb.
=> Fixed bug where Ray2/Aabb2 intersection returned false positives for rays parallel to an axis

src/ray.rs
Creates a new ray based on ray + transform
=> Adding ray transform function. 

src/bound.rs, src/frustum.rs, src/lib.rs, src/line.rs, src/plane.rs, src/ray.rs, src/traits.rs, src/volume/aabb/mod.rs, src/volume/cylinder.rs, src/volume/obb.rs, src/volume/sphere.rs, tests/aabb.rs, tests/bound.rs, tests/frustum.rs, tests/plane.rs, tests/point.rs, tests/sphere.rs
Also updated the text in lib.rs
=> Removing license header from source files

Cargo.toml, benches/polyhedron.rs, src/algorithm/broad_phase/brute_force.rs, src/algorithm/broad_phase/mod.rs, src/algorithm/broad_phase/sweep_prune.rs, src/algorithm/mod.rs, src/lib.rs
Two algorithms for now:
- Brute force - does bounding box intersection tests for all shape pairs in the given world
- Sweep and prune - See the documentation for more information.
=> Adding broad phase collision detection algorithms

src/algorithm/minkowski/gjk/mod.rs, src/algorithm/minkowski/gjk/simplex/mod.rs, src/algorithm/minkowski/gjk/simplex/simplex2d.rs, src/algorithm/minkowski/gjk/simplex/simplex3d.rs, src/primitive/util.rs
Using the GJK distance algorithm.
=> Adding distance computation between convex shapes

src/algorithm/minkowski/gjk/mod.rs, src/contact.rs, src/traits.rs
Also adding distance computation for complex shapes
=> Adding time of impact computation using GJK

src/algorithm/minkowski/gjk/mod.rs
To avoid issues with numerical stability
=> Making time of impact computation return a full contact manifold

src/algorithm/broad_phase/dbvt.rs, src/algorithm/broad_phase/sweep_prune.rs, src/algorithm/minkowski/gjk/mod.rs, src/algorithm/minkowski/gjk/simplex/simplex2d.rs, src/algorithm/minkowski/gjk/simplex/simplex3d.rs, src/dbvt/mod.rs, src/plane.rs, src/primitive/particle.rs, src/primitive/polyhedron.rs, src/primitive/util.rs, src/volume/aabb/aabb2.rs
Also ran rustfmt-nightly.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/55)
=> feat: Add FaceIterator for external access to faces in ConvexPolyhedron

src/primitive/capsule.rs, src/primitive/cylinder.rs, src/primitive/mod.rs, src/primitive/polyhedron.rs, src/primitive/primitive3.rs, src/primitive/util.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/56)
=> feat: Cylinder and capsule primitives

src/algorithm/broad_phase/dbvt.rs, src/dbvt/mod.rs, src/dbvt/util.rs, src/traits.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/57)
=> fix: Remove Debug bounds on generic types

src/primitive/capsule.rs, src/primitive/cylinder.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/58)
=> fix: Expose volume parameters for cylinder and capsule

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/62)
=> fix: Add gitter badge

benches/dbvt.rs, src/algorithm/broad_phase/brute_force.rs, src/algorithm/broad_phase/mod.rs, src/algorithm/broad_phase/sweep_prune.rs, src/dbvt/mod.rs, src/dbvt/wrapped.rs, src/primitive/capsule.rs, src/primitive/circle.rs, src/primitive/cuboid.rs, src/primitive/cylinder.rs, src/primitive/mod.rs, src/primitive/polygon.rs, src/primitive/polyhedron.rs, src/primitive/primitive2.rs, src/primitive/primitive3.rs, src/primitive/rectangle.rs, src/primitive/sphere.rs, src/traits.rs, src/volume/aabb/mod.rs, src/volume/sphere.rs, tests/dbvt.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/59)
=> feat: Make it possible to be abstract over bounding volumes

src/algorithm/broad_phase/sweep_prune.rs, src/bound.rs, src/dbvt/mod.rs, src/dbvt/visitor.rs, src/dbvt/wrapped.rs, src/frustum.rs, src/prelude.rs, src/primitive/mod.rs, src/traits.rs, src/volume/aabb/aabb3.rs, src/volume/aabb/mod.rs, src/volume/sphere.rs, tests/aabb.rs, tests/bound.rs, tests/point.rs
Depends on #63. This is a breaking change.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/64)
=> fix: Rename Bound and BoundingVolume

rustfmt.toml, src/dbvt/visitor.rs, src/dbvt/wrapped.rs, tests/aabb.rs, tests/point.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/65)
=> Formatting changes from new rustfmt

CHANGELOG.md, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/66)
=> Updated changelog and bumping version before release

Cargo.toml, src/contact.rs, src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/67)
=> Reducing serde dependencies

Cargo.toml, src/primitive/capsule.rs, src/primitive/circle.rs, src/primitive/cylinder.rs, src/primitive/polygon.rs, src/primitive/polyhedron.rs, src/primitive/sphere.rs, src/primitive/util.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/68)
=> fix: Upgrade to cgmath 0.16

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/69)
=> Update version for release

CHANGELOG.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/kvark/collision-rs/70)
=> fix: Changelog for v0.14

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/78)
=> Fix README paths

src/primitive/cuboid.rs, src/primitive/rectangle.rs
Fixes #75.
cc @msiglreith
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/77)
=> fix: Expose dimensions of Rectangle/Cuboid

Cargo.toml, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/80)
=> fix: Update metadata after organisation move

src/algorithm/minkowski/epa/epa2d.rs, src/algorithm/minkowski/epa/epa3d.rs, src/algorithm/minkowski/epa/mod.rs, src/algorithm/minkowski/gjk/mod.rs, src/line.rs
Fixes #76.
cc @msiglreith @kvark
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/79)
=> feat: Expose tolerance settings on GJK/EPA

README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/81)
=> fix: License

src/line.rs, src/primitive/cuboid.rs, src/primitive/line.rs, src/primitive/mod.rs, src/primitive/primitive2.rs, src/primitive/primitive3.rs, src/primitive/quad.rs, src/primitive/rectangle.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/83)
=> feat: Add more primitives

CHANGELOG.md
After #83 .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/84)
=> Changelog 0.15

src/dbvt/util.rs
After #84
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/85)
=>  feat: Add utility function that returns all values in DBVT that intersects a given ray

benches/dbvt.rs, src/algorithm/broad_phase/dbvt.rs, src/algorithm/broad_phase/sweep_prune.rs, src/algorithm/minkowski/epa/epa2d.rs, src/algorithm/minkowski/epa/epa3d.rs, src/algorithm/minkowski/gjk/mod.rs, src/dbvt/mod.rs, src/dbvt/util.rs, src/frustum.rs, src/line.rs, src/plane.rs, src/primitive/cylinder.rs, src/primitive/line.rs, src/primitive/polygon.rs, src/primitive/polyhedron.rs, src/primitive/util.rs, src/ray.rs, src/traits.rs, src/volume/aabb/aabb2.rs, src/volume/aabb/mod.rs, src/volume/sphere.rs, tests/dbvt.rs
There is still a few Clippy suggestions left that I didn't apply, either because I disagreed with them or they touch public APIs. I can open a new PR with the ones touching public APIs, or add them to this PR, if you want. But this will already fix the bulk of potential style issues the current clippy version (0.0.188) can detect.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/86)
=> Make the code more idiomatic (thanks to clippy)

Cargo.toml, src/dbvt/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/87)
=> fix: Add Default implementation for DynamicBoundingVolumeTree

Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/89)
=> Bump rand version -> 0.4

CHANGELOG.md, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/90)
=> fix: Update dependencies, and prepare for release

src/primitive/cuboid.rs, src/primitive/mod.rs, src/primitive/primitive2.rs, src/primitive/primitive3.rs, src/primitive/rectangle.rs
Fixes #73 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/91)
=> feat: Add Cube and Square primitives

.travis.yml, Cargo.toml, src/contact.rs, src/frustum.rs, src/lib.rs, src/line.rs, src/plane.rs, src/primitive/capsule.rs, src/primitive/circle.rs, src/primitive/cuboid.rs, src/primitive/cylinder.rs, src/primitive/particle.rs, src/primitive/polygon.rs, src/primitive/polyhedron.rs, src/primitive/primitive2.rs, src/primitive/primitive3.rs, src/primitive/quad.rs, src/primitive/rectangle.rs, src/primitive/sphere.rs, src/ray.rs, src/volume/aabb/aabb2.rs, src/volume/aabb/aabb3.rs, src/volume/cylinder.rs, src/volume/obb.rs, src/volume/sphere.rs, tests/serde.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/92)
=> Rename eders to serde

CHANGELOG.md, Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/93)
=> Update changelog and version for release

src/algorithm/minkowski/gjk/simplex/simplex2d.rs, src/algorithm/minkowski/gjk/simplex/simplex3d.rs, src/plane.rs, src/primitive/polyhedron.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/103)
=> Refactor a bit of code based on compiler warnings and clippy

CHANGELOG.md, Cargo.toml
Updated CHANGELOG.md to include the changes for v0.19 and v0.20.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/112)
=> 0.20.1 Updated CHANGELOG.md.

CHANGELOG.md, Cargo.toml, README.md, benches/dbvt.rs, benches/polyhedron.rs, src/algorithm/minkowski/epa/epa2d.rs, src/algorithm/minkowski/epa/epa3d.rs, src/algorithm/minkowski/gjk/mod.rs, src/algorithm/minkowski/gjk/simplex/simplex2d.rs, src/algorithm/minkowski/gjk/simplex/simplex3d.rs, src/plane.rs, src/primitive/capsule.rs, src/primitive/circle.rs, src/primitive/cuboid.rs, src/primitive/cylinder.rs, src/primitive/particle.rs, src/primitive/polygon.rs, src/primitive/polyhedron.rs, src/primitive/rectangle.rs, src/primitive/sphere.rs, src/primitive/util.rs, tests/aabb.rs, tests/bound.rs, tests/dbvt.rs, tests/frustum.rs, tests/plane.rs, tests/point.rs, tests/serde.rs, tests/sphere.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/123)
=> Remove unneeded extern crate and replace approx with cgmath

.github/workflows/ci.yml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/125)
=> fix some mistake

.github/workflows/ci.yml, README.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/126)
=> Replace the badge for the status of the CI

src/algorithm/broad_phase/brute_force.rs, src/algorithm/broad_phase/dbvt.rs, src/algorithm/broad_phase/sweep_prune.rs, src/contact.rs, src/lib.rs, src/primitive/polyhedron.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/127)
=> Fix some warnings

rustfmt.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/128)
=> Remove unknown option in rustfmt.toml

rustfmt.toml, src/dbvt/mod.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rustgd/collision-rs/129)
=> Some fmt option and typo fix
